### ISSUE TITLE
Chat Formatting only formats chat on the server console, not in game.

### ISSUE THREAD

**Issue by Cerealistic** [EternalCodeTeam/ChatFormatter#100]
![image](https://github.com/EternalCodeTeam/ChatFormatter/assets/117193440/be9b6dc2-0f19-4700-bb33-2a77e1f86bf7)
Proper Formatting in console.
![image](https://github.com/EternalCodeTeam/ChatFormatter/assets/117193440/b731794b-5e71-4f7a-b90a-a2cbf97ef8c9)
Wrong formatting in server chat.

This has happened with every chat plugin I have used so far, except LuckPermsChat, but I would prefer to use ChatFormatter. Please figure out a fix to this error.

**Comment by vLuckyyy** [comment]
See plugin list

**Comment by Cerealistic** [comment]
AdvancedAntiLag, AdvancedEnchantments, AdvancedGUI, AdvancedHelp, AdvancedReplay, AuctionHouse, AuctionHouseAntiDupe, AuthMe, AutoPluginUpdater, BlueSlimeCore, BrandBlocker, ChatControl, ChatFormatter, Chunky, ChunkyMap, Citizens, CombatLogX, CommandAliases, CompatNoCheatPlus, CraftEnhance, CustomDeathMessages, DailyRewardsPlus, DeluxeMenus, DeluxeTags, DiscordSRV, dynmap, EconomyShopGUI-Premium, EconomyX, EliteLootbox, Factions, FactionsBridge, FactionsTop, HolographicDisplays, IllegalStack, InteractiveChat, InvSeePlusPlus, IPWhitelist, JoinCore, LagAssist, Lores*, LPC, LuckPerms, NoCheatPlus, Orebfuscator, Pl-Hide-Pro, PlaceholderAPI, PlugManX, PrivateMessages, ProtocolLib, RoseStacker, RTP, SafeNBT, SecureServerBackup, ServerRules, ServersNPC, SetHome*, SetSpawn, SilkSpawners, SimpleTpa*, SkinsRestorer, spark, SuperVanish, TAB, TerraformGenerator, UberEnchant, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WhoIs, WorldEdit, WorldGuard

**Comment by vLuckyyy** [comment]
You are using interactivechat, lpc and chatformatter at the same time?

**Comment by Cerealistic** [comment]
> You are using interactivechat, lpc and chatformatter at the same time? Just use only chatformatter

LPC and InteractiveChat are both disabled. InteractiveChat is used for hover text and items.

**Comment by vLuckyyy** [comment]
> > You are using interactivechat, lpc and chatformatter at the same time? Just use only chatformatter
> 
> LPC and InteractiveChat are both disabled. InteractiveChat is used for hover text and items.

ChatFormatter has option to hovers, just disable all plugins working with chat and check again.

**Comment by Cerealistic** [comment]
> > > You are using interactivechat, lpc and chatformatter at the same time? Just use only chatformatter
> > 
> > 
> > LPC and InteractiveChat are both disabled. InteractiveChat is used for hover text and items.
> 
> ChatFormatter has option to hovers, just disable all plugins working with chat and check again.

Okay, this did nothing.

**Comment by vLuckyyy** [comment]
It's likely not a chatformatter problem. You can test this by setting up an empty server with only the necessary plugins required for chatformatter to function properly.
