### ISSUE TITLE
<rainbow> chat permission missing?

### ISSUE THREAD

**Issue by FaultyFunctions** [EternalCodeTeam/ChatFormatter#131]
Hello! I am using Chat Formatter v1.2.0 on a purpur 1.20.4 server. I'm not sure how to give my players the ability to use the <rainbow> color. There doesn't seem to be a permission for it and chatformatter.color.* doesn't seem to be working.

**Comment by P1otrulla** [comment]
@FaultyFunctions Sorry for the long wait, the rainbow permission has been added **chatformatter.rainbow**, it's still waiting for the main release but you can download from github actions here: [rainbow-jar](https://github.com/EternalCodeTeam/ChatFormatter/actions/runs/10165206920/artifacts/1756113992)
