### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to ChatFormatter v1.0.5

### ISSUE THREAD

**Issue by Legnatbird** [EternalCodeTeam/ChatFormatter#75]
Purpur 1.19.3-1916
![image](https://user-images.githubusercontent.com/50637445/219710352-aff0e132-941b-4902-9607-53703baea983.png)

**Comment by vLuckyyy** [comment]
You must install any permission plugin, such as LuckPerms or else, and please update your plugin version to 1.0.6.

**Comment by Legnatbird** [comment]
Thanks bro ^^
