### ISSUE TITLE
Messages sent are not picked up by DiscordSRV

### ISSUE THREAD

**Issue by Complex1t** [EternalCodeTeam/ChatFormatter#82]
Hello, loving the plugin with its simplicity and features. I have one concern: messages sent in the chat using this plugin are not picked up by DiscordSRV. Would there be any way to fix it?

**Comment by vLuckyyy** [comment]
Try enabling preFormatting option in config

**Comment by Complex1t** [comment]
I have enabled the preFormatting option, and the chat formatting stopped working and I am getting this error in the console after doing so: https://pastebin.com/y5q8JGnd

Here is my config.yml:
https://pastebin.com/WpK8yKda

**Comment by Jakubk15** [comment]
Would you mind providing us a complete set of plugins used on your server? Furthermore, please tell us the content of the message you are sending.

**Comment by Complex1t** [comment]
Apologies for the late response, I have been pretty busy for the past week.

I have done some testing, and it seems like when using the preFormatting option, using any placeholders from PlaceholderAPI in the message format will result in the error and formats not applying. The issue occurs when any message is sent - the content of the message doesn't matter.

Here is the list of plugins I had during my testing:
ChatFormatter 1.0.7 & ChatFormatter PaperSupport 1.0.7
EssentialsX 2.19.7
LuckPerms 5.4.62
PlaceholderAPI 2.11.1
Vault 1.7.3

Additionally, even when using the preFormatting option (and removing all placeholders so no errors occur), DiscordSRV still doesn't pick up any messages.

**Comment by justinhschaaf** [comment]
Running into the same issue with ChatFormatter v1.0.7 and DiscordSRV v1.26.2. Enabling the `preFormatting` option yields a [near identical error](https://gist.github.com/justinhschaaf/59e16b3b281b7968341d3ccb5ffe95dc) to the one posted in https://github.com/EternalCodeTeam/ChatFormatter/issues/82#issuecomment-1528921599 and also breaks the custom format I have set, while the format works and doesn't give an error with `preFormatting` disabled. Neither send the messages to Discord. Here are my config files for both ChatFormatter and DiscordSRV:

- [ChatFormatter `config.yml`](https://gist.github.com/justinhschaaf/59f7d642c221834bc63df11c32e2122e)
- [DiscordSRV `config.yml` (with my bot token and channel/role ids redacted)](https://gist.github.com/justinhschaaf/085c8428f3344ac35ea23cc677cb2e6c)

It's possible my configuration is wrong; however, I doubt it as chat messages were being sent to Discord before installing ChatFormatter.

**Comment by jefflima1** [comment]
I have the same problem, is there a solution for this? discordsrv fails to capture server messages

**Comment by vLuckyyy** [comment]
This will most likely be fixed in the next release, thanks for reporting issue.

**Comment by failutee** [comment]
> Apologies for the late response, I have been pretty busy for the past week.
> 
> I have done some testing, and it seems like when using the preFormatting option, using any placeholders from PlaceholderAPI in the message format will result in the error and formats not applying. The issue occurs when any message is sent - the content of the message doesn't matter.
> 
> Here is the list of plugins I had during my testing: ChatFormatter 1.0.7 & ChatFormatter PaperSupport 1.0.7 EssentialsX 2.19.7 LuckPerms 5.4.62 PlaceholderAPI 2.11.1 Vault 1.7.3
> 
> Additionally, even when using the preFormatting option (and removing all placeholders so no errors occur), DiscordSRV still doesn't pick up any messages.

```
public static String toBukkitFormat(String text) {
        return text
            .replace("<displayname>", "%1$s")
            .replace("<message>", "%2$s");
}
```

This function replaces `<displayname>` and `<message>` from what I've noticed you're using `{displayname}` and `{message}`  
and the plugin can't set the format correctly. Replacing **{ ... }** with **< ... >** should do the trick

**Comment by vLuckyyy** [comment]
> > Apologies for the late response, I have been pretty busy for the past week.
> > I have done some testing, and it seems like when using the preFormatting option, using any placeholders from PlaceholderAPI in the message format will result in the error and formats not applying. The issue occurs when any message is sent - the content of the message doesn't matter.
> > Here is the list of plugins I had during my testing: ChatFormatter 1.0.7 & ChatFormatter PaperSupport 1.0.7 EssentialsX 2.19.7 LuckPerms 5.4.62 PlaceholderAPI 2.11.1 Vault 1.7.3
> > Additionally, even when using the preFormatting option (and removing all placeholders so no errors occur), DiscordSRV still doesn't pick up any messages.
> 
> ```
> public static String toBukkitFormat(String text) {
>         return text
>             .replace("<displayname>", "%1$s")
>             .replace("<message>", "%2$s");
> }
> ```
> 
> This function replaces `<displayname>` and `<message>` from what I've noticed you're using `{displayname}` and `{message}` and the plugin can't set the format correctly. Replacing **{ ... }** with **< ... >** should do the trick

placeholders with **{ ... }** is built-in custom placeholders.

```
placeholders:
  {displayname}: "<displayname>"
  {message}: "<message>"
  ```
